
// This file was auto-generated by ML.NET Model Builder. 

using PricePredictionModelConsole;

// Create single instance of sample data from first line of dataset for model input
PricePredictionModel.ModelInput sampleData = new PricePredictionModel.ModelInput()
{
    CPU = @"i5",
    GPU = @"intel",
    RAM = 4F,
    RAMType = @"ddr3",
    Storage = 500F,
    SSD = false,
    Weight = 2F,
};


Console.WriteLine("Usando modelo de IA para fazer uma única previsão -- Comparando preço real com o preço estipulado pelo modelo...\n");

Console.WriteLine($"CPU: {@"i9"}");
Console.WriteLine($"GPU: {@"intel"}");
Console.WriteLine($"RAM: {16F}");
Console.WriteLine($"RAMType: {@"ddr5"}");
Console.WriteLine($"Storage: {512F}");
Console.WriteLine($"SSD: {true}");
Console.WriteLine($"Weight: {4F}");
Console.WriteLine($"Price: {700F}");

var predictionResult = PricePredictionModel.Predict(sampleData);
Console.WriteLine($"\n\nCom estes componentes acima, o preço estipulado pelo modelo é aproximadamente: US${predictionResult.Score}\n\n");

Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

